/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nidonuevo.model;

import java.io.File;
import java.io.FilenameFilter;

/**
 *
 * @author TOSHIBA
 */
public class loadGame extends java.awt.Dialog {

    /**
     * Creates new form getName
     */
    public loadGame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setLocation(430,300);
        initComponents();
        String[] fileNames; // For the filename declaration
        String directory= System.getProperty("user.dir");     
      

        File dir = new File(directory);
       fileNames=new String[dir.list().length];
       fileNames =dir.list(new FilenameFilter() {
    public boolean accept(File directory, String fileName) {
        return fileName.endsWith(".bin");
    } });      
       
       
       for (int i=0;i<fileNames.length;i++){
           choice1.add(fileNames[i]);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        choice1 = new java.awt.Choice();
        button1 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        panel1.setPreferredSize(new java.awt.Dimension(500, 70));

        label1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        label1.setText("¿Nombre del archivo a abrir?");
        panel1.add(label1);
        panel1.add(choice1);

        button1.setLabel("Ok");
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        panel1.add(button1);

        add(panel1, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
        click_ok=true;
        
        setVisible(false);
        dispose();
    }//GEN-LAST:event_button1MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */

    public String name;
    private boolean click_ok=false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Choice choice1;
    private java.awt.Label label1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the click_ok
     */
    public boolean isClick_ok() {
        return click_ok;
    }
    public String sel(){
        return choice1.getSelectedItem();
    }

    /**
     * @param click_ok the click_ok to set
     */
    public void setClick_ok(boolean click_ok) {
        this.click_ok = click_ok;
    }
}
